// <auto-generated />
using System;
using GymApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260613133225_UpdateGymClassSeed")]
    partial class UpdateGymClassSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GymApp.Server.Models.GymClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("GymClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 6, 14, 11, 30, 0, 0, DateTimeKind.Local),
                            MaxCapacity = 15,
                            Name = "Joga dla początkujących",
                            Room = "Sala A (Lustrzana)",
                            StartTime = new DateTime(2026, 6, 14, 10, 0, 0, 0, DateTimeKind.Local),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 6, 14, 18, 0, 0, 0, DateTimeKind.Local),
                            MaxCapacity = 12,
                            Name = "Intensywny CrossFit",
                            Room = "Strefa Wolnych Ciężarów",
                            StartTime = new DateTime(2026, 6, 14, 17, 0, 0, 0, DateTimeKind.Local),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2026, 6, 15, 19, 0, 0, 0, DateTimeKind.Local),
                            MaxCapacity = 20,
                            Name = "Trening Cardio",
                            Room = "Sala B (Rowery)",
                            StartTime = new DateTime(2026, 6, 15, 18, 0, 0, 0, DateTimeKind.Local),
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("GymApp.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymApp.Server.Models.GymClass", b =>
                {
                    b.HasOne("GymApp.Server.Models.User", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
